name: Payments Tests

on: [push]

concurrency:
  group: payments-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_build:
    name: Lint & Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

  unit_integration:
    name: Unit & Integration
    runs-on: ubuntu-latest
    needs: lint_build
    timeout-minutes: 25
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run unit tests
        run: yarn test:unit

      - name: Run integration tests
        env:
          TEST_SUBSCRIBER_API_KEY: ${{ secrets.TEST_SUBSCRIBER_API_KEY }}
          TEST_BUILDER_API_KEY: ${{ secrets.TEST_BUILDER_API_KEY }}
          TEST_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
        run: yarn test:integration

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    needs: unit_integration
    continue-on-error: true
    timeout-minutes: 40
    env:
      TEST_SUBSCRIBER_API_KEY: ${{ secrets.TEST_SUBSCRIBER_API_KEY }}
      TEST_BUILDER_API_KEY: ${{ secrets.TEST_BUILDER_API_KEY }}
      TEST_ENVIRONMENT: staging_sandbox
      NVM_FRONTEND_URL: https://api-base-sepolia.staging.nevermined.app/
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run E2E tests
        run: yarn test:e2e --detectOpenHandles


